# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIO0Su93F1Dz8g5hc5DgMQDOsNLWgaAo
"""

import matplotlib.pyplot as plt

import numpy as np

x = np.array(['610','611','611A','612'])

y = np.array([20,25,21,18])

plt.bar(x,y)

plt.show()

import matplotlib.pyplot as plt

import numpy as np

x = np.array([90,25,25,15])

mylabels = ["suniy intelekt", "kiberxavfsizlik", "differensial t", "algaritm"]

plt.pie(x, labels=mylabels, startangle=90)

plt.show()

import matplotlib.pyplot as plt

import numpy as np

x = np.array([35,25,25,15])

mylabels = ["Malumotlar bazasi", "tizimli dasturlash", "sun'iy intelekt", "kiberxavfsizlik"]

myexplode = [0.2, 0, 0, 0]

plt.pie(x, labels=mylabels,

startangle=90,explode=myexplode)

plt.show()